/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var n = Object.defineProperty;
var h = Object.getOwnPropertyDescriptor;
var r = Object.getOwnPropertyNames;
var g = Object.prototype.hasOwnProperty;
var c = (t, e) => {
    for (var s in e) n(t, s, { get: e[s], enumerable: !0 });
  },
  u = (t, e, s, l) => {
    if ((e && typeof e == "object") || typeof e == "function")
      for (let i of r(e))
        !g.call(t, i) &&
          i !== s &&
          n(t, i, {
            get: () => e[i],
            enumerable: !(l = h(e, i)) || l.enumerable,
          });
    return t;
  };
var p = (t) => u(n({}, "__esModule", { value: !0 }), t);
var m = {};
c(m, { default: () => o });
module.exports = p(m);
var a = require("obsidian"),
  o = class extends a.Plugin {
    constructor() {
      super(...arguments);
      this.refresh = () => {
        this.updateStyle();
      };
      this.updateStyle = () => {
        (document.body.classList.toggle(
          "hider-status",
          this.settings.hideStatus,
        ),
          document.body.classList.toggle("hider-tabs", this.settings.hideTabs),
          document.body.classList.toggle(
            "hider-scroll",
            this.settings.hideScroll,
          ),
          document.body.classList.toggle(
            "hider-sidebar-buttons",
            this.settings.hideSidebarButtons,
          ),
          document.body.classList.toggle(
            "hider-tooltips",
            this.settings.hideTooltips,
          ),
          document.body.classList.toggle(
            "hider-search-suggestions",
            this.settings.hideSearchSuggestions,
          ),
          document.body.classList.toggle(
            "hider-file-nav-header",
            this.settings.hideFileNavButtons,
          ),
          document.body.classList.toggle(
            "hider-search-counts",
            this.settings.hideSearchCounts,
          ),
          document.body.classList.toggle(
            "hider-instructions",
            this.settings.hideInstructions,
          ),
          document.body.classList.toggle(
            "hider-meta",
            this.settings.hidePropertiesReading,
          ),
          document.body.classList.toggle(
            "hider-vault",
            this.settings.hideVault,
          ));
      };
    }
    async onload() {
      (await this.loadSettings(),
        this.addSettingTab(new d(this.app, this)),
        this.addCommand({
          id: "toggle-tab-containers",
          name: "Toggle tab bar",
          callback: () => {
            ((this.settings.hideTabs = !this.settings.hideTabs),
              this.saveData(this.settings),
              this.refresh());
          },
        }),
        this.addCommand({
          id: "toggle-hider-status",
          name: "Toggle status bar",
          callback: () => {
            ((this.settings.hideStatus = !this.settings.hideStatus),
              this.saveData(this.settings),
              this.refresh());
          },
        }),
        this.refresh());
    }
    onunload() {}
    async loadSettings() {
      this.settings = Object.assign({}, b, await this.loadData());
    }
    async saveSettings() {
      await this.saveData(this.settings);
    }
  },
  b = {
    hideStatus: !1,
    hideTabs: !1,
    hideScroll: !1,
    hideSidebarButtons: !1,
    hideTooltips: !1,
    hideFileNavButtons: !1,
    hideSearchSuggestions: !1,
    hideSearchCounts: !1,
    hideInstructions: !1,
    hidePropertiesReading: !1,
    hideVault: !1,
  },
  d = class extends a.PluginSettingTab {
    constructor(e, s) {
      (super(e, s), (this.plugin = s));
    }
    getSettingDefinitions() {
      return [
        {
          type: "group",
          heading: "Interface",
          items: [
            {
              name: "隐藏标签栏",
              desc: "隐藏窗口顶部的标签栏容器。",
              control: { type: "toggle", key: "hideTabs" },
            },
            {
              name: "隐藏状态栏",
              desc: "隐藏字数、字符数与反向链接数量显示。",
              control: { type: "toggle", key: "hideStatus" },
            },
            {
              name: "隐藏库名称",
              desc: "隐藏你的库个人信息栏。警告：此操作同时会隐藏设置按钮与库切换图标。你可以使用快捷键或命令面板打开对应功能。",
              control: { type: "toggle", key: "hideVault" },
            },
            {
              name: "隐藏滚动条",
              desc: "隐藏全部滚动条。",
              control: { type: "toggle", key: "hideScroll" },
            },
            {
              name: "隐藏侧边栏切换按钮",
              desc: "隐藏两侧侧边栏的切换按钮。",
              control: { type: "toggle", key: "hideSidebarButtons" },
            },
            {
              name: "隐藏悬浮提示",
              desc: "隐藏所有悬浮提示。",
              control: { type: "toggle", key: "hideTooltips" },
            },
          ],
        },
        {
          type: "group",
          heading: "File explorer",
          items: [
            {
              name: "隐藏文件资源管理器按钮",
              desc: "隐藏文件资源管理器顶部的各类按钮（新建文件、新建文件夹等）。",
              control: { type: "toggle", key: "hideFileNavButtons" },
            },
          ],
        },
        {
          type: "group",
          heading: "Search",
          items: [
            {
              name: "隐藏搜索建议",
              desc: "隐藏搜索面板中的推荐词条。",
              control: { type: "toggle", key: "hideSearchSuggestions" },
            },
            {
              name: "隐藏搜索关键词匹配数量",
              desc: "隐藏每条搜索结果内的匹配条目数量。",
              control: { type: "toggle", key: "hideSearchCounts" },
            },
          ],
        },
        {
          type: "group",
          heading: "Other",
          items: [
            {
              name: "隐藏操作提示文字",
              desc: "隐藏快速切换器与命令面板内的操作指引提示。",
              control: { type: "toggle", key: "hideInstructions" },
            },
            {
              name: "在阅读视图中隐藏属性栏",
              desc: "隐藏阅读视图里的属性板块。",
              control: { type: "toggle", key: "hidePropertiesReading" },
            },
          ],
        },
      ];
    }
    async setControlValue(e, s) {
      (await super.setControlValue(e, s), this.plugin.refresh());
    }
  };
